# ADMIN_PASSWORD: FreshRSS admin login, set at first boot via unattended install.
# ADMIN_API_PASSWORD: separate password gating the Fever/GReader API (mobile apps).
apiVersion: v1
kind: Secret
metadata:
  name: freshrss-secret
stringData:
  ADMIN_PASSWORD: ENC[AES256_GCM,data:YXvzVr8S06uCCXS9WjgemdEUpx8=,iv:4yOcorVPujHBuY1krE9Cp7JSk83j7m9VKVr6M6tjcvo=,tag:urTa5hXwDYrKPyA8TP7mVw==,type:str]
  ADMIN_API_PASSWORD: ENC[AES256_GCM,data:D1E3dAf/MVpSvu6jB864I3TodimIlm7m2kv5In80uWcJwTMYJJOxlGhO839QASY=,iv:My9pEwC8hFkyVH7Pq6NcOnfX10pwnn2yiIFqLNbHkT8=,tag:XioulJ29DB+HZ4rfG1XAHg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzelZuZC82Q2Q3cWVuSU5o
        dnlHZThsbno1blNWZmdGRngxVHpWamFaOGhrClI3T1VOYzQxNmI0NlZDNlVUVmNY
        ajlWODM4YXBUdzRpWVd2N0V5N3dUWVkKLS0tIDFKb0RkTUY4cjhaNm1IOVBlODlp
        OExYUnNxMlFwVHNCOWIvUktkRW5ER28KZDEW+cULGtdRAD0cHJygfTXRphp0/OPV
        3SMlHrdlCVMv3q68mul+feB8lqMXCdh8kiJ3rE41bG5Ph1dwjLypHQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gekuxnpd95l5j8gsvmpsn2mewnevd0c5y5v66p4trzcqhmpn0svqkmnyy7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-09T17:34:30Z"
  mac: ENC[AES256_GCM,data:L9Ub2ZZZnIpL4QT/wJlX/TyjhU6iTw7O4tUYHkraMgA7slMPnrlICwiydwOs9r7uh6z8kmFV5FVslmW/ZPR/2ZJoyMhdG67oSFjPoWsT5+898wZWd8HE1TTECH6egR6NFCigLXdtTIVAY/+OB2sNCIvLCP4WBV6dPD2jeyXuUYQ=,iv:Tj07RalWCM+Va5vH/Hx5ThdcWzg54NwIpDGNXcfVFSQ=,tag:Xl2f1mzoRxbRknWAfLmYhg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
