---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrepository.yaml
  - ./helmrelease.yaml
  - ./httproute-s3.yaml
  - ./httproute-console.yaml
  - ./probe-bucket-metrics.yaml
  - ./minio-root-credentials.sops.yaml
  - ./recording-annotator-minio-user-credentials.sops.yaml
  - ./recording-annotator-user-bootstrap-job.yaml
