# SOPS-encrypted Secret — real ciphertext, managed by the repo age key.
apiVersion: v1
kind: Secret
metadata:
  name: recording-annotator-minio-root-credentials
  namespace: storage
stringData:
  rootUser: ENC[AES256_GCM,data:1whF+73u2yq3dDHlqEUaQck83+ZgI6D/,iv:qYsaTFEBOtZ3kGSUvBl1IvHulPfya4TXf70LX3om3ZA=,tag:7lmJtsivDjG/nqIzLOZKHA==,type:str]
  rootPassword: ENC[AES256_GCM,data:NAWd+bhh8LmI0CgbR2CuCxhZq2g+tcCUyYqgz+1AejieLC7Zy8Lllg==,iv:eTiBozZSKR6gD+y0xre4UVQ/UnKeljK+BntIbslcllw=,tag:oj0BbAAvXn0MhpVd7erZ3A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVkk2RmdacTJDQkRMMjlJ
        L2VTWWl1cHJGVUdlTEcrME1FRnB5NFJkMnljClJDRTNqeitGY0xKRXhpNWd4SnE5
        Vi9rWHJ4YUR5VnhJN3I1UGpvTDJoU1EKLS0tIDdVajJWVEhjT2RTRVZydmptdEFK
        UTJVdzRCdm8vekRod1dFVS9GVytWQlEKPmO7XAhb7bwKIwkRqDhp2FjJrFyq7KAw
        jZbzCgnK6XrcGTzV7uhjH5XP6UKV6uKH5hZ34ExZVFV43eVLPitudA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gekuxnpd95l5j8gsvmpsn2mewnevd0c5y5v66p4trzcqhmpn0svqkmnyy7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-01T12:54:58Z"
  mac: ENC[AES256_GCM,data:EYy7T1Nwr6PmjlZ8pB0vPGggpgstVvv00f6PSdpeZiyIlnGpWpEY0vluI/LhWEgMH9/NMHE639UUrMax27mCLDLD7TO5bT41W5RNF68Xgg3tKb7dAQbAQ1qPTsT8gZ8bqZxrXaLPhEVxXH0jsReyN2NBKhDtwgI1LqJeswiavow=,iv:pjbB4BuRiHtE2V3t9k1puNtgAiID6jk+vG23wQpYBfM=,tag:6f5nBNS/dKGbXixLxz+uqQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
