---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app prowlarr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/prowlarr
              tag: nightly-2.3.6.5351-ls229
            env:
              PGID: "1001"
              PUID: "1001"
              TZ: ${TIMEZONE}
              UMASK: "002"
            resources:
              requests:
                cpu: 25m
                memory: 256Mi
              limits:
                memory: 2Gi

    defaultPodOptions:
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [1001]

    service:
      main:
        controller: main
        ports:
          http:
            port: &port 9696

    route:
      main:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: prowlarr
          gethomepage.dev/title: Prowlarr
          gethomepage.dev/description: "Indexer Manager for Arr Apps"
          gethomepage.dev/group: "Downloads"
        hostnames:
          - prowlarr.${SECRET_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: main
                port: *port

    persistence:
      config:
        existingClaim: prowlarr-config
        globalMounts:
          - path: /config

      tmp:
        type: emptyDir