---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: knative-smoke
spec:
  dependsOn:
    - name: knative-serving
      namespace: flux-system
  interval: 1h
  path: ./kubernetes/apps/default/knative-smoke/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false
