# Fill these values, then re-encrypt in place if changed:
# sops --encrypt --in-place kubernetes/apps/default/hermes-ai-agent/app/secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: hermes-ai-agent-secret
  namespace: default
  labels:
    app.kubernetes.io/name: hermes-ai-agent
type: Opaque
stringData:
  #ENC[AES256_GCM,data:j7nVolfz5Z+NiuHOElIHQL3JHchhRaWbOIJqnnTZX4aMsZ0W+7h/SkL6+qCyi9YybodZfUkBik3qXON+s4LzFNCFaC2CkTZ0SUI=,iv:OsqmVBOeVFhIGsWN8odFO4iTjE2UtDc6RVbRS1M46YI=,tag:kgcaUS/A5WPA2zbZeePjgg==,type:comment]
  API_SERVER_KEY: ENC[AES256_GCM,data:H4rX1ca1lliv8QAvCuZCnZMhlRJaZhh6JP1OIEIAx2OO5cgxgOzEg6ZRFZoxVpKW39cqPRraP0K4Aa4DSqqtug==,iv:NAT1WwhwHnVnaT1z95BIP7ltMpNxy7XUNoqYZjOrjuY=,tag:vM1gq/RDrjSF+vgZ0CU1uQ==,type:str]
  HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ""
  HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ""
  HERMES_DASHBOARD_BASIC_AUTH_SECRET: ""
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkU3MrTzQ0MmJSTldDYnJX
        d3NML0s2bVJEblI5NUtzQ0lBNzhXb3R5VnhJCk9FcVQwSE9kSEQwTzFqODY2cWRw
        V0g2R0RobldIaWRaMVlrOGFDWVZ3VTQKLS0tIFAzZDl6Ny9WWFJIWTlvQ21NdFg1
        WXorS0RVZlV6aVFGazlVRjYzUjBCOUEKkPhNwNxAbBCByIZppJIpHGizJiBY/CgH
        +PVTNSO0siwGB3D0Kg37Cplp0MGd5RuG/rafR74lcL8DHBgsZtjQbA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gekuxnpd95l5j8gsvmpsn2mewnevd0c5y5v66p4trzcqhmpn0svqkmnyy7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-20T13:51:43Z"
  mac: ENC[AES256_GCM,data:kGVGDKYQVvNeUO2ZoEDjDiB5SI2YK8WRnlVof1KeI3PUonosz20XsYyCE7Wzh0DkuV4qi6Rh8S1c88JYYCKwmohCqpXCYSJmHmBdTqwOOVfEs5lj5N5onVtA/31h5CbmneT0PKmM7+oce7yX0TgJEFdT05gSrfUOoGKTCN/eSW8=,iv:rnJBpNhdmOwpV+6oY65i0fOzxpB1TayZVY/uJh7PF5w=,tag:AA8WgV54kLvGQEvBzxhMMQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
