---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kroki
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/yuzutech/kroki
              tag: 0.28.0
            env:
              KROKI_PORT: &port "8000"
            resources:
              requests:
                cpu: 25m
                memory: 256Mi
              limits:
                memory: 1Gi

    service:
      main:
        controller: main
        ports:
          http:
            port: *port

    route:
      main:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: https://kroki.io/assets/logo.svg
          gethomepage.dev/title: Kroki
          gethomepage.dev/description: "Create diagrams from textual descriptions"
          gethomepage.dev/group: "Tools"
        hostnames:
          - kroki.${SECRET_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: main
                port: *port
