---
version: '3'

set: [pipefail]
shopt: [globstar]

vars:
  BOOTSTRAP_DIR: '{{.ROOT_DIR}}/bootstrap'
  KUBERNETES_DIR: '{{.ROOT_DIR}}/kubernetes'
  SCRIPTS_DIR: '{{.ROOT_DIR}}/scripts'
  TALOS_DIR: '{{.ROOT_DIR}}/talos'
  PRIVATE_DIR: '{{.ROOT_DIR}}/.private'
  TALOSCONFIG: '{{.ROOT_DIR}}/talos/clusterconfig/talosconfig'

env:
  KUBECONFIG: '{{.ROOT_DIR}}/kubeconfig'
  SOPS_AGE_KEY_FILE: '{{.ROOT_DIR}}/age.key'
  TALOSCONFIG: '{{.TALOSCONFIG}}'
  SECRET_DOMAIN: 'koopmans.co'
  TIMEZONE: 'America/Chicago'

includes:
  bootstrap: .taskfiles/bootstrap
  talos: .taskfiles/talos
  template: .taskfiles/template
  sops: .taskfiles/sops

tasks:

  default: task --list

  apply:
    desc: Apply a App Kustomization resource for a cluster
    summary: |
      Args:
        path: Path under apps containing the  app (required)
    cmd: |
      TMP_APP_DIR="$(mktemp -d)"
      trap 'rm -rf "$TMP_APP_DIR"' EXIT
      cp -R "{{.KUBERNETES_DIR}}/apps/{{.path}}/app/." "$TMP_APP_DIR/"

      find "$TMP_APP_DIR" -type f -name "*.sops.*" | while IFS= read -r encrypted_file; do
        sops --decrypt "$encrypted_file" > "$encrypted_file.tmp"
        mv "$encrypted_file.tmp" "$encrypted_file"
      done

      kustomize build "$TMP_APP_DIR" | envsubst | \
      kubectl apply --kubeconfig {{.KUBECONFIG}} --server-side \
          --field-manager=kustomize-controller -f -
    requires:
      vars: ["path"]
    vars:
      ns: '{{.ns | default "flux-system"}}'
    preconditions:
      - { msg: "Missing kubeconfig", sh: "test -f {{.KUBECONFIG}}" }

  remove:
    desc: Remove a App Kustomization resource for a cluster while testing
    summary: |
      Args:
        path: Path under apps containing the  app (required)
    cmd: |
      TMP_APP_DIR="$(mktemp -d)"
      trap 'rm -rf "$TMP_APP_DIR"' EXIT
      cp -R "{{.KUBERNETES_DIR}}/apps/{{.path}}/app/." "$TMP_APP_DIR/"

      find "$TMP_APP_DIR" -type f -name "*.sops.*" | while IFS= read -r encrypted_file; do
        sops --decrypt "$encrypted_file" > "$encrypted_file.tmp"
        mv "$encrypted_file.tmp" "$encrypted_file"
      done

      kustomize build "$TMP_APP_DIR" | envsubst | \
      kubectl delete --kubeconfig {{.KUBECONFIG}} -f -
    requires:
      vars: ["path"]
    vars:
      ns: '{{.ns | default "flux-system"}}'
    preconditions:
      - { msg: "Missing kubeconfig", sh: "test -f {{.KUBECONFIG}}" }



  build:
    desc: build Resources at a given path using customize and test against kubeconform
    summary: |
      Args:
        path: Path under apps containing the Flux Kustomization resource (ks.yaml) (required)

    cmd: |
      TMP_APP_DIR="$(mktemp -d)"
      trap 'rm -rf "$TMP_APP_DIR"' EXIT
      cp -R "{{.KUBERNETES_DIR}}/apps/{{.path}}/app/." "$TMP_APP_DIR/"

      find "$TMP_APP_DIR" -type f -name "*.sops.*" | while IFS= read -r encrypted_file; do
        sops --decrypt "$encrypted_file" > "$encrypted_file.tmp"
        mv "$encrypted_file.tmp" "$encrypted_file"
      done

      kustomize build "$TMP_APP_DIR" | envsubst

    requires:
      vars: ["path"]
    preconditions:
      - { msg: "Missing kubeconfig ", sh: "test -f {{.KUBECONFIG}}" }
      - { msg: "Missing Flux Kustomization for app {{.path}}", sh: "test -f {{.KUBERNETES_DIR}}/apps/{{.path}}/ks.yaml" }


  validate:
    desc: Run an asset through the validation offered by kubeconform
    summary: |
      Args:
        path: Path under apps containing the Flux Kustomization resource (ks.yaml) (required)
    cmd: |
      bash {{.SCRIPTS_DIR}}/kubeconform.sh {{.KUBERNETES_DIR}}
    preconditions:
      - { msg: "Missing kubeconfigflux ", sh: "test -f {{.KUBECONFIG}}" }


  reconcile:
    desc: Force Flux to pull in changes from your Git repository
    cmd: flux --namespace flux-system reconcile kustomization flux-system --with-source
    preconditions:
      - test -f {{.KUBECONFIG}}
      - which flux
