# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrepository.yaml
  - ./helmrelease.yaml
  - ./minio-root-credentials.sops.yaml
  - ./bucket-bootstrap-job.yaml
  - ./bucket-quota-bootstrap-job.yaml
  - ./probe-bucket-metrics.yaml
  - ./thanos-user-credentials.sops.yaml
  - ./thanos-user-bootstrap-job.yaml
  - ./loki-user-credentials.sops.yaml
  - ./loki-user-bootstrap-job.yaml
