apiVersion: v1
kind: Secret
metadata:
  name: loki-user-credentials
  namespace: storage
stringData:
  accessKey: ENC[AES256_GCM,data:6EU15I7tXWOa3RkhYnkRonYhFe+y,iv:Zlg6cL4QjXC2GJfkULAePQ1afyjReUul0tvn7zDcIl4=,tag:a+PylgpXkWWs3+WJIma8tA==,type:str]
  secretKey: ENC[AES256_GCM,data:LCi8z+ei6ZgHbX7S/rjOncjx7h+1cgZwW7piNlG8yhOYwYDINtLYsw==,iv:UaceiCt9vqLTPlYgYrzMrOl0K72SOSg4l/2bW9k3Hq8=,tag:UPrk5RtpHdgF6GfKcL2/Ww==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VGIvUm9nMzMrdDVXR1I0
        VzRmYjc3cEVFdG9CR2I5YjdXR1h0Ujd3YTNNCm9pUWpYL1NMdUErRTErcEFaTHlE
        cHFONHI2MG1GNTlORElsYkQrYXY3cUUKLS0tIDhyTG1CSjJxODZLOHR5T0ZTQ29z
        eVRxYWlGdVNVYXpxUDBsWTN0WVhJNTgKvAW9VLF7x68fO51z23IOmv4u5a8GYfsR
        AXJ8jxSxBT6rE+xzEItJ77cE/gvR03Ry1dk57Ef4AHQiU4tNojloGA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gekuxnpd95l5j8gsvmpsn2mewnevd0c5y5v66p4trzcqhmpn0svqkmnyy7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-03T16:01:59Z"
  mac: ENC[AES256_GCM,data:CGY6mKy8mGsvwM+izjY+z0OoKq6vdsyQHr8WWgHMCAZKK5HocaKwjlMo4hsLDiEJ6enrCUHUKw2qIvRDq3evj3chypE7J3L1tKTvKXDndwiClDSRoEkNcLzRqvVjG2uHRPH/2Ed1E0STgW56GAxw+pCKtJNJuHQDb6y9SIT461A=,iv:tQM5u1WmXjVYywL5xQ6XAL983UnuLPTryxZWiPUHsf4=,tag:NzoU7zoemlFcvUaVyble/g==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
