apiVersion: v1
kind: Secret
metadata:
  name: minio-root-credentials
  namespace: storage
stringData:
  rootUser: ENC[AES256_GCM,data:ShRqHz7JtL5/vSq+7rj7RA==,iv:RwJL3g9BqAvjHGxeb6yfnPOLXvlEUo/897m689QQprw=,tag:iSjckPRtcmmmy3oKFRTqzg==,type:str]
  rootPassword: ENC[AES256_GCM,data:Do46eWiCzvF+LxBn59EQoA==,iv:iRjKvfLszvQ+GSNwJ13D0f8ovPsi5wVDpyzL6zZ3Ucg=,tag:ezJFZ2cyRVpMOl8VL5zAvA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTDhOV2VNQ3c0ZDVFWktJ
        K3Bzem9DVTJmWFVjQkZFcmtwVllRVHhmNmhvCnJRSkhqUmZGdzhLckhOa1hxUlZG
        WitZemhoZ21SVk1UZmJMdzUyMTBOY1EKLS0tIHJPd3I5NXdCVGlvTFppcC8rZExJ
        bW5zNUFEdXpjTEV4ZnNjd01ZSGNLSW8KQH+Gp+xl2L+5v7s708xOzuJE+s7+Leaf
        uuarjcs3R9sMAALwuIJp8Cvr75Mr4N0Cu4GJ1PqpQ1Dpsuypq7fOeQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gekuxnpd95l5j8gsvmpsn2mewnevd0c5y5v66p4trzcqhmpn0svqkmnyy7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-03T01:01:40Z"
  mac: ENC[AES256_GCM,data:G6Wz8HZu4PnQsHtTEWmhjnAiiTYV37DLa0Fy5pWfYDK5o+7DDyywflMsToPOVFLNoKQQ+x9hvvndJvAm2F/CQucsCgjoVz9+FdbiQXn8ds8tV0IThWJfGhRzvy/6CD4PLhJLOZvsIO1mpyb5G1Xb35uwIS27e7lNo23c0lRxwek=,iv:rghL7C5SHvQ4/Z0+3uEDxVdBp7erhkeLTgJRWOvv/VI=,tag:N2tIcPY3XA34cXcHVdPXYw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
