apiVersion: v1
kind: Secret
metadata:
  name: thanos-user-credentials
  namespace: storage
stringData:
  accessKey: ENC[AES256_GCM,data:xswAras5lUhB0PasdagEL1SKTUUAYLs=,iv:r2bPXALClLIHyDL9mnJAJ3azN/UULcj3e3CmfF/lcTk=,tag:ImKs3JhdOj9SumtOU7YhtA==,type:str]
  secretKey: ENC[AES256_GCM,data:nT0XBAHWg1ZPeDOz9MveV7aeQP1tObi4dvmxPVvcBJHmR88wbCSLYQ==,iv:a+0M9WlfrDo5uIoq/G0V7N9nr+t1yXl4K8Seq93vBAg=,tag:q33Lx2ai4SQ26P8BU9fm5w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqeUZMTFFBZGsyWVNLM0k0
        Y1FXN0ZrQjIzTnZ6YW1STmN5NWVOV2YyY3pzCmx1MDF0QzRVWkY4VlhiU2FvcXY3
        MXl6dFFXOFlieWdGZm5ReVRjbmpnUG8KLS0tIG42dmU3Q1NjSXNVSE1yODRSNW5R
        aWtxRUVpdllBWGxsb25iVWdkL2ltd2sK93ANnmkdvkQxKU6U6x8zBDMUGUFGlTUr
        mfjsNKY9uspcFOuDk3IulUyB3FJ+LJXcw3yn/iiCztsz5/Tzfbd7MQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gekuxnpd95l5j8gsvmpsn2mewnevd0c5y5v66p4trzcqhmpn0svqkmnyy7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-03T02:26:55Z"
  mac: ENC[AES256_GCM,data:iavmP3Tf7pGM88x4u5ogRSFwzQFHJyY1oKMH4gC1+Pumxdn9f8561fJ0/WHCkZdJWf5o1PDv4a6aKlKmgkkr+xKGp72uk68I5MDcb8DeKyLTfXBSBXHD4v+rvW3XMV8Voo3SPvclbiT7u8eUIbottpXhnUigcXLx8bBzR2ptBOg=,iv:HxcYrjtJN/8nzUAZgyUkkA/5TAMPEAIv+tAGdPFx2Y8=,tag:MPdWG4hATpbGsQ1x5eF57g==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
