---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: n8n
  namespace: default
  labels:
    app.kubernetes.io/name: n8n
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: n8n
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      scheme: http
      interval: 30s
