---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: monitoring
data:
  config.alloy: |
    logging {
      level  = "info"
      format = "logfmt"
    }

    discovery.kubernetes "pods" {
      role = "pod"
      selectors {
        role  = "pod"
        field = "spec.nodeName=" + sys.env("NODE_NAME")
      }
    }

    loki.source.kubernetes "pods" {
      targets    = discovery.kubernetes.pods.targets
      forward_to = [loki.write.default.receiver]
    }

    loki.relabel "syslog_labels" {
      forward_to = [loki.write.default.receiver]

      rule {
        action        = "replace"
        source_labels = ["__syslog_connection_ip_address"]
        target_label  = "source_ip"
      }

      rule {
        action        = "replace"
        source_labels = ["__syslog_message_hostname"]
        target_label  = "hostname"
      }

      rule {
        action        = "replace"
        source_labels = ["__syslog_message_app_name"]
        target_label  = "app_name"
      }

      rule {
        action        = "replace"
        source_labels = ["__syslog_message_severity"]
        target_label  = "severity"
      }

      rule {
        action        = "replace"
        source_labels = ["__syslog_message_facility"]
        target_label  = "facility"
      }
    }

    loki.source.syslog "syslog" {
      relabel_rules = loki.relabel.syslog_labels.rules
      listener {
        address  = "0.0.0.0:5143"
        protocol = "udp"
        labels   = {
          job = "syslog",
        }
      }
      forward_to = [loki.write.default.receiver]
    }

    loki.write "default" {
      endpoint {
        url = "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
      }
    }
