---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mcp

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./mcp-grafana-lifeos/ks.yaml
  - ./mcp-grafana-monitoring/ks.yaml
  - ./mcp-kubernetes/ks.yaml
  - ./mcp-playwright/ks.yaml
  - ./mcp-postgres/ks.yaml
  - ./mcp-prometheus/ks.yaml
