apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:RlfsV+6MC71M3qI=,iv:QgywaW84n8VYVEdtpQl+rYGhvwR2rhRRoI7IN4nfOHI=,tag:ZoE2vCPzEKlSc+j5OCeYYA==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:wdT8ghrrJQVR6sGQ//OU,iv:i4MihqigHJ/MBOreaylM8gyszaH0BdBC+Wf5rVjn0rQ=,tag:ajieyXk6HtVJsE3sN2RBhQ==,type:str]
sops:
    age:
        - recipient: age1gekuxnpd95l5j8gsvmpsn2mewnevd0c5y5v66p4trzcqhmpn0svqkmnyy7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBd3lrL0xRdGZPSTl4Z2tR
            ZmVCU3c4ZXNvYldLNU5UNmlhK2dIMmZIbFFRCm9jQnNPVTdOdlJuR3V0M3djVjBj
            K29meU1nZG1Id3FxV2FIWS9NTUIwbXcKLS0tIDgwQ0Jmd25tNXRCbVJhWXZGOXJu
            OUNadTViaThMVU83ekd5a1FqcEE3emsKDYhAz/XVpDLCnQ/h8P9SOD9MsAeqUnpR
            XKvBW91Nk2ByVT5dJtXkhkrg5VlQ3kGvFXQ9bGuXzD0lUYBoE0VxAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T14:35:03Z"
    mac: ENC[AES256_GCM,data:QaLQzvpfgUDw21Ai/MF+zNSCdi10rUyecYArZQp3HtmtqjstfJO502G1LLqcUztDOizzZOBymRETeEhCpd3/B5H7HxsqmZ/6mqg/sqMPZTmSLrO8gHnLnnqESA9TtGOpjz3axfBqcnZRHOPfEDXfCWaB6zycZengir8nBouzzrE=,iv:KPFKn1Juv3sIPpG50nAHA32UzmvK+9yi4xzIZSh4zsM=,tag:1k5GZe+E4vCZBKW4Dh6C7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
