# Fill these values, then encrypt in place:
# sops --encrypt --in-place kubernetes/apps/default/obsidian-sync/app/secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: obsidian-sync-secret
  namespace: default
  labels:
    app.kubernetes.io/name: obsidian-sync
type: Opaque
stringData:
  #ENC[AES256_GCM,data:b+YafTvYTVvfxGvZ35+6jbhKuFecrslDgHKVApe3JxsRYpBksXjFClRZYpUB/YOEsgmhJyYrahQ1yNVgHSlinuhqNkI=,iv:/TsNXimTCuNgT1XZ4kc6VSVkiS8rwdtaUkAr41yP874=,tag:glOtNHieg92D+oj/0x4elQ==,type:comment]
  OBSIDIAN_ACCOUNT_EMAIL: ""
  OBSIDIAN_ACCOUNT_PASSWORD: ""
  #ENC[AES256_GCM,data:aIkeSpsxAn40Z2Xm9rd8jrFGeAAdX8jUN3eTAVrcBd2NgmPTrvER,iv:5sWJ5Bay6lxyobIGkY7ZKDFMD6VskU6A9l4GgRHJX90=,tag:+GJuHDRaGRZNTQ+BBw/+ng==,type:comment]
  OBSIDIAN_ACCOUNT_MFA: ""
  #ENC[AES256_GCM,data:2JRg8d/xv71RKtmquR+h77mQQMH+H/Ylqyc=,iv:yjLZaKBv/RExgW27+dbACHhN68SRpoPTR9bDGcY83oM=,tag:x1aUJ9JzvQWqDdiKOlYCqA==,type:comment]
  OBSIDIAN_SYNC_PASSWORD: ""
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOXVMRStHNjNwbUwydWdh
        anI5aTdKTTZPVFNjd1hUb2owY0JkdkhvNlRNCmFJWDlpbmwyRm9FUWlodUxrT2JK
        NFI5UE1qV3pMc2tVYllNYXQzS2dycWcKLS0tIEV6eFB4NHZ1RFRiOUc5WnFRNGpu
        eVp4WVF4S1hLWkgxM3VLM09zUThsZTAKGMo4YApOQUQIvOir6+dvbS/uHD2pPXZw
        MckrcroxCGTizED2jx7gT3EH5/aT5KwgpB111otUpBucr45tMLBdYw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gekuxnpd95l5j8gsvmpsn2mewnevd0c5y5v66p4trzcqhmpn0svqkmnyy7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-23T13:16:33Z"
  mac: ENC[AES256_GCM,data:0TITkp+/5QTHCbei8G1mmyV1X8w8MQ54yauXbgMptyktJJTgqoZ8N390sZT12rLj/WuOcK/E3L8k/INHh+Qft9lXRWYzJky+E/XLdGyOWwKqfcp7Qf7MB9idyjn/xwxMNUkB3vcE2YE6Me4rlDbYvTVr2YKOvhESREeDUqYhdF4=,iv:pXTspO+5BajMvyLlRQ5Mck68Wtcw8XPXnNy1xKw7Dj0=,tag:IdlqSuYujbiAt3EX/2GYaQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
