# Fill these values, then encrypt in place:
# sops --encrypt --in-place kubernetes/apps/default/obsidian-sync/app/secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: obsidian-sync-secret
    namespace: default
    labels:
        app.kubernetes.io/name: obsidian-sync
type: Opaque
stringData:
    #ENC[AES256_GCM,data:b+YafTvYTVvfxGvZ35+6jbhKuFecrslDgHKVApe3JxsRYpBksXjFClRZYpUB/YOEsgmhJyYrahQ1yNVgHSlinuhqNkI=,iv:/TsNXimTCuNgT1XZ4kc6VSVkiS8rwdtaUkAr41yP874=,tag:glOtNHieg92D+oj/0x4elQ==,type:comment]
    OBSIDIAN_ACCOUNT_EMAIL: ENC[AES256_GCM,data:AknW6/HsdORosqpLqqHw8OjeiE0+ttEp,iv:+FvmmJoLaMoT3ZvuQ69mw+ucDkMlrMkrq0hl0pJKrf0=,tag:5r0jkbGqUecOu/hz3cPsng==,type:str]
    OBSIDIAN_ACCOUNT_PASSWORD: ENC[AES256_GCM,data:Vn1p/Wm5eEOOLA==,iv:e67J9Nkc8u+Q2nfsGVSsNyvhA7bGzeP6ZqOo3NnY4P4=,tag:2QvLJlj6MxA24GXUDZD0Ww==,type:str]
    #ENC[AES256_GCM,data:aIkeSpsxAn40Z2Xm9rd8jrFGeAAdX8jUN3eTAVrcBd2NgmPTrvER,iv:5sWJ5Bay6lxyobIGkY7ZKDFMD6VskU6A9l4GgRHJX90=,tag:+GJuHDRaGRZNTQ+BBw/+ng==,type:comment]
    OBSIDIAN_ACCOUNT_MFA: ""
    #ENC[AES256_GCM,data:2JRg8d/xv71RKtmquR+h77mQQMH+H/Ylqyc=,iv:yjLZaKBv/RExgW27+dbACHhN68SRpoPTR9bDGcY83oM=,tag:x1aUJ9JzvQWqDdiKOlYCqA==,type:comment]
    OBSIDIAN_SYNC_PASSWORD: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOXVMRStHNjNwbUwydWdh
            anI5aTdKTTZPVFNjd1hUb2owY0JkdkhvNlRNCmFJWDlpbmwyRm9FUWlodUxrT2JK
            NFI5UE1qV3pMc2tVYllNYXQzS2dycWcKLS0tIEV6eFB4NHZ1RFRiOUc5WnFRNGpu
            eVp4WVF4S1hLWkgxM3VLM09zUThsZTAKGMo4YApOQUQIvOir6+dvbS/uHD2pPXZw
            MckrcroxCGTizED2jx7gT3EH5/aT5KwgpB111otUpBucr45tMLBdYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gekuxnpd95l5j8gsvmpsn2mewnevd0c5y5v66p4trzcqhmpn0svqkmnyy7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T22:04:35Z"
    mac: ENC[AES256_GCM,data:7aPCj8BwS+TxhMhUvOLWfeIBBFdXhaJqSB3rLvHH8JUCwm1E6TCAebV00JpWHVrk0BFpzV+Z8j0jKZpqsGjwS5tKR13CYMBxmNqiL8Ffbc5jv7li8KNynq4lCF3J3/yFPrL3f9HaPV4DtbnCKAmBBLr3J6z+K3C8Tx7hh33gR6U=,iv:PiNM/46pPlqIDlYrzRerPK0rInw8fZJqJ3OxHfCAJ5A=,tag:MO1uCHwyIQed1wK5NjXWlQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
