apiVersion: v1
kind: Secret
metadata:
  name: guacamole-secret
type: Opaque
stringData:
  #ENC[AES256_GCM,data:oUxOPRg1D+5J1ER6xnUhQuwEl/9wZBFxQHbqL3+dkQqlMIt4ps8Xsg9bcQgX2YPYUXQvGrCwKZimUeADo84vSpmhwBxvtOtLbLye,iv:qhK9sFf2pXNm9yUglwUKfXSzCWro7oBo1n0oacm9Bk4=,tag:S8CLXl3Ejf6R3jGF20PYGA==,type:comment]
  postgres-user: ENC[AES256_GCM,data:LUvoE1VMkn8f,iv:ezrdSbdxfbF90oSox5xdovkjbFqTxgnNcKfkOezFwW0=,tag:zQJkhkRDHfgZVllx+dLRZQ==,type:str]
  #ENC[AES256_GCM,data:jbMdJsGUzJX0EW3fn75gtnbbZc1WLDH5kjYI1aror3MPplGnEeomp2jjqXMLVlGVd/MeTaSZo4VlQG6MyeBlBrlL,iv:BkHXXx7Q/WV+Gx8cipvVGSF6LyEcZ7wpdQPn8TiZe6c=,tag:I9N/0aBODZkNDI6PqsYCdg==,type:comment]
  postgres-password: ENC[AES256_GCM,data:Kqeh/IaHUczZ3J05laULDF2oXTlZ46os88k06A==,iv:dfojFFVsX3UqN0SFpAvf2nSH+hvUALEGqvEI1DpPR5s=,tag:BC60hNgStF0pCC4zmbTjFw==,type:str]
  #ENC[AES256_GCM,data:oveFjRzvIyZzEh8Flq47aGNeawNBNecQkyceXdvKIfSHlmeh+KRbTdx4CuwSnsMasLnhYpFnnzs2QvqZuOfcyl79OIf5t7YE+7Po9xs5,iv:SsE/Z1Q5PkzxrJf2cS4iR7pRGczzDrd/ePdSdp1Hi6A=,tag:6664zYgWK6KsdJw/t7rRaw==,type:comment]
  #ENC[AES256_GCM,data:dSI2ji3h/9nBDdH6NaqO6gRrO5iqiVAnsbIRS4/cfgablUiSZxZ410ZeYIpK8Jo7rNABUeB/BU+8AAv8nMulA0oQlbEZJIa3zQ==,iv:QiKdoPx/vjJ6OZiWf4oPgENNkrk8ONlS+ej6tetspN0=,tag:w5VLaHL6TKVe1MImwNPp+Q==,type:comment]
  vnc-host: ENC[AES256_GCM,data:g3lsJEMzNZWoJZcjfzb+vAN0pkBqog==,iv:KzC6NnLhyHruXsM4ORFkBEg/Qyk0BYfebj5jcQevW9g=,tag:3NvnAjEBHSIkMRdolcgljA==,type:str]
  vnc-port: ENC[AES256_GCM,data:jno1tA==,iv:E+AekaQyOn/024oeq8yHUYNBgRSa92/qs0osPer3NA8=,tag:JHuxwFVPNrrVFeXo7k+YfQ==,type:str]
  #ENC[AES256_GCM,data:xmXm5HwOsofmTD4ZyDdsbLUE6O2D0vrq70CWMj/A6Q7zjvK+S2B1d9DZ3ZRWGjtun8IkN8w+iNRyKUtO8H+W+GYNs6xXZg==,iv:bt7wR0IXFUCjwnPmOOrx/5wziy1b2xzeiMsEcQZw15o=,tag:TyIoguHlYmIre1lFWgwYTA==,type:comment]
  vnc-password: ENC[AES256_GCM,data:CtRGtMp2hS30DiZ7JpWZhZgymYIUjAA=,iv:MlWY3BkRPub3haUYlWLIa0nbEnJXH3qSDRN3Mw4mDEQ=,tag:/ZzdVgIuHEsP6v0wPre6Hg==,type:str]
  #ENC[AES256_GCM,data:HCjtqn+APYtPSLs4LrxR7SseaklHKEL3sRqIAgmvD611EIkiXWyTZH+QLwjSAABHxh76PgyMsiLMrM4Vj2yaj8DMhlIvPtl8nTc9zPLWV9kZzyog+cs=,iv:PuLQKYb5xoor8NfTPhQoOqSo5nr4lcOQUzAye5YXVYk=,tag:COjq7n8uqKwdqQw5YFYlHw==,type:comment]
  #ENC[AES256_GCM,data:w6pxh4lhblKvULDplqiW6Jo/Y+j4+h1jcbGYbYPED0f1edKPH6vi8Yei36gu92vZz/gqeaIjHDqeHdAaCAXAKRCsb61Wi1J28+g=,iv:Rktg9gfg+PKHZCG2eXrjLOQmf2F439aN8Dk02PzTQ/U=,tag:EnRdQ3iTQwHD8/MY9SIUoQ==,type:comment]
  #ENC[AES256_GCM,data:q2OA7JgkRF7+TCm+g78adsuTsjcWNjDVKFxAsVmblNmu6syDKsMFZGrjNsTMZ2OSOJTiqqOhgkRts1cIV7LXzDazDO2e,iv:nLt58gh53rz+8PLI2Rp3a8UiKNWbgtXdcyCagylwYmA=,tag:B2JJw0TAIsFr2CCgLxARdg==,type:comment]
  michele-email: ENC[AES256_GCM,data:gqyhzBOH0vhHmYnMqTYgIB7F+/hj+13/KkyPGTSi,iv:sW7ptfX/24t/ZqFViVWwCuAb+V0Mv6lIqDZrZz/SNCM=,tag:MFj0PlIFzTQToyG9ix5EIw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Z2szUVB1UXFUVENPWlJ2
        TGxEUkZxWVlQT2ErYWxqenVwVDhKUy9lMGxZClhaSzFPdFJpWEU3ZzIxVTBjc3Zl
        dXo5bjNIZDFzREM2bmFydmFQZEtoSFkKLS0tIEh0U05MSGo4VThRN2VBLzAvZ1hD
        aFU4TW5LaUEwRTVHdCt4LzY2L29NaVUKbqE38gRDFsQHIkGe2DPC11e8iAfcmMVD
        qblICl9zgEEpaoUSv74ty26BLrP6ez5DzcCYvWUouzpA6E3gU0Vw7g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gekuxnpd95l5j8gsvmpsn2mewnevd0c5y5v66p4trzcqhmpn0svqkmnyy7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-12T21:40:32Z"
  mac: ENC[AES256_GCM,data:jFoLtXXcniWLnUT77XHXSAA8uNmATRGy8PzDnmECx6i4NC6lgISpQtCNyn2Rag2cMtQDU3m89U9zpAJp1rPo5hloZVVY4E1s2qcxgTG8SzjHr7LXMTDE+2OkqfGoi6XrKTOXIx3XXiZExis4zQw44ZDAee+Lanu5AR3WtVSv87E=,iv:MaCqNH/VkJZPal46A+YkNYUM467zmIvnXUt5c297u6A=,tag:LLgCqBGHrtoTyS2DyYotWg==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
