apiVersion: v1
kind: Secret
metadata:
    name: guacamole-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:gruKA3B3QyYOGmD8z0B2Ptd2ZxKAqP9xjMNvifk+IMhlZWg/P7NQYlqkfHuTWeq7wAvaHMwOgs6ybanL4tLb7HDEHyXljy70MRz5,iv:7GvZs14E5J33vrCqxPSGHJSpyXUYjwq961IzWXiFInQ=,tag:rc1k+5BYdFsK5LTu0BykPQ==,type:comment]
    #ENC[AES256_GCM,data:srv6n00vVfo+WWcQ3E6rmU+uJk7vIehs8vS2iJaanpojLldpqdMRAFkOiO3PixwXXMY2aggXgi2TOYcTrwByA/nkWqWtrmzo9uM=,iv:B+X+P1o1TipQXYDZcj+gSjOLP3X1vv8vb2kVGurL7hI=,tag:nQeKCYerCIHobSIdqewLFA==,type:comment]
    #ENC[AES256_GCM,data:Oi1muewbQuOtWOsoAD3BuRcALgdNRk9yGD1NO5Plg5hhcwYc8Ms6IDTtkmBRCm2bWFRtrfqlEfORsBzFqqC8f75zn8xrZoH7ncI=,iv:jmtwUB3gO9POwX+wRidiiyK2eR5iH4kG8WES3xGjAcI=,tag:0f2SsM/adlasyHyfCIctmg==,type:comment]
    #ENC[AES256_GCM,data:GL4dFwhZ8lyNTrPOxvzGrkAMYgy4UjTk/V7Nt/PYgojgOkGwEcAmLOfEigHWKAPHjoAycCjrswMG3Yp02Hca,iv:mDy14ZNkckLRinXabraM8QwysOv2fZ+NkADn/wCDE14=,tag:MtTGp2T2/xqQ6cMG2G1lIg==,type:comment]
    #
    #ENC[AES256_GCM,data:Fh9x7mFsnQ/Oe2CT9C4AuAye8wBh38wjqxFHCUrqUAJRRRUeQ3WvzYpb+xA7jbVBLzGnzOKsY5VBseqFao6ijgVA,iv:iLoRcPYaYl9gJg1UyUxcBRUzplUAtMJ9L3UOWP3WlSg=,tag:DF3fuK/SF/9RiISH9UfZ7g==,type:comment]
    #ENC[AES256_GCM,data:hoHLFS2oQEC3dkH2e1oNveXPR2+Us5AoBykNE3CUaNsimIFm9KA5M9lSzRv7H7gVq8vhvWuRaj4oL6OdfjWaJ6KcuMr17azv,iv:HbzCxUvEh3KXFZLNKdr0fBuxvHcCL3zpFBdEbnDZoAQ=,tag:xLTEK7yoLTffMvzX1+tW4Q==,type:comment]
    #ENC[AES256_GCM,data:8rzOtZxf+g91S4/Yst3M60IVD49S/mnARsNpKtitarEQENOTdPtg/IbXNVud,iv:Z++LbSfC7BhvSiGCN2+kLgb37M95tdwcVZgOtE/qSJM=,tag:s/0E6lYKu+6LbWHpPAJeAA==,type:comment]
    user-mapping.xml: ENC[AES256_GCM,data:W0oRTQKBiLfsgcBQnaLmKdK242h9VTOagQS8Erug68xQT4GMwOoCFoNKPl7PNNrSZ9WoWnw2iolnjOa9emZg/SKDuWGRHMKPy+Fe/fYDf78CSQoV0QO9bYT3pw3M6L/+I9Q2mDHiYAWgyTDvaLZkJoo2PiXRldACbuTMqzHpNzwmjVqs2ccdlwXdvIvMp5sKYiC5MOmwCp2lYYFXY7HzZK/WiF6fF+D+HTY/Nsjzr7u9iJQOt9SBHDCM/f6Oum7/dP1BWBtzFdoFS6vvQuc2MY1YDOoq8UPfgQmw1WwPnLQwRo0ihvM1ynwQ3/2ywXIXHs6YXyd6CCF3b1tpueJKb5/6DjBZRZYslinVvAdzo8k6DP1Ozt2aTGEyVO3kgbEnpuKLRySWAkAQm7Mm2JN97enpVWcW7JEEZK/jOXYxZmog514ePGwWfZHFolATGMbwsebawrTmOXS+w0Tn/OSHGozXxv9raXevYU1OgQ82FF2JNSq3QMYVBiwTXYmIrfprg8pvZuAmYA==,iv:YVDin1BXnQIV5fJbHZ2OTa5OOWSOOthlxeqCNqdSjVY=,tag:pJth1mloMEd7H6BEWgq9bg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNkhwcXpNZ2pvcGFOMjg4
            K2NteFFjSnNKTlBCZnlCMGhLZmVjUWFTRUNVCk4yblZLOHRaUGRCKzEvd1RzL1RN
            UXpSemgyTFlRSXQ0dmJBL0pMMHBkZVEKLS0tIDMvVFBhSk9mQTg0TUt2YksxSG5k
            dnBKemI5RjFacThzRm1UMVBZSHNOR0kKAHsH7+zpn4WjCk8X4Uk+gRtJpVzWmWPV
            tMQ3NNdeIsWDx1HXZVErMaDSL711rDfL820Bs0+BupJPjYX2k8+SpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gekuxnpd95l5j8gsvmpsn2mewnevd0c5y5v66p4trzcqhmpn0svqkmnyy7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T05:37:40Z"
    mac: ENC[AES256_GCM,data:x8+uYjqaibfdLgMQJfmVefljukfTuAwQ/OzgKvG7+EVYV4wXq5h2aFeJ7JvbKFUKstKuELbADztOJyxDnLq2gzE5FpIOf4gWTwl4Tl0I/mr5+TvNyd9jWkXoD2OE1RtKGF/OLrbZlCMgF70I9ExGQEnUokhsoXanZBQjUzptquo=,iv:px8nWKggkypK5YoThVnBzYIYy1kFDl15s6AtS/U+1lM=,tag:RCEQscXL6uCEwsp9LTueXQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
