apiVersion: v1
kind: Secret
metadata:
  name: guacamole-secret
type: Opaque
stringData:
  #ENC[AES256_GCM,data:gruKA3B3QyYOGmD8z0B2Ptd2ZxKAqP9xjMNvifk+IMhlZWg/P7NQYlqkfHuTWeq7wAvaHMwOgs6ybanL4tLb7HDEHyXljy70MRz5,iv:7GvZs14E5J33vrCqxPSGHJSpyXUYjwq961IzWXiFInQ=,tag:rc1k+5BYdFsK5LTu0BykPQ==,type:comment]
  #ENC[AES256_GCM,data:srv6n00vVfo+WWcQ3E6rmU+uJk7vIehs8vS2iJaanpojLldpqdMRAFkOiO3PixwXXMY2aggXgi2TOYcTrwByA/nkWqWtrmzo9uM=,iv:B+X+P1o1TipQXYDZcj+gSjOLP3X1vv8vb2kVGurL7hI=,tag:nQeKCYerCIHobSIdqewLFA==,type:comment]
  #ENC[AES256_GCM,data:Oi1muewbQuOtWOsoAD3BuRcALgdNRk9yGD1NO5Plg5hhcwYc8Ms6IDTtkmBRCm2bWFRtrfqlEfORsBzFqqC8f75zn8xrZoH7ncI=,iv:jmtwUB3gO9POwX+wRidiiyK2eR5iH4kG8WES3xGjAcI=,tag:0f2SsM/adlasyHyfCIctmg==,type:comment]
  #ENC[AES256_GCM,data:GL4dFwhZ8lyNTrPOxvzGrkAMYgy4UjTk/V7Nt/PYgojgOkGwEcAmLOfEigHWKAPHjoAycCjrswMG3Yp02Hca,iv:mDy14ZNkckLRinXabraM8QwysOv2fZ+NkADn/wCDE14=,tag:MtTGp2T2/xqQ6cMG2G1lIg==,type:comment]
  #
  #ENC[AES256_GCM,data:Fh9x7mFsnQ/Oe2CT9C4AuAye8wBh38wjqxFHCUrqUAJRRRUeQ3WvzYpb+xA7jbVBLzGnzOKsY5VBseqFao6ijgVA,iv:iLoRcPYaYl9gJg1UyUxcBRUzplUAtMJ9L3UOWP3WlSg=,tag:DF3fuK/SF/9RiISH9UfZ7g==,type:comment]
  #ENC[AES256_GCM,data:hoHLFS2oQEC3dkH2e1oNveXPR2+Us5AoBykNE3CUaNsimIFm9KA5M9lSzRv7H7gVq8vhvWuRaj4oL6OdfjWaJ6KcuMr17azv,iv:HbzCxUvEh3KXFZLNKdr0fBuxvHcCL3zpFBdEbnDZoAQ=,tag:xLTEK7yoLTffMvzX1+tW4Q==,type:comment]
  #ENC[AES256_GCM,data:8rzOtZxf+g91S4/Yst3M60IVD49S/mnARsNpKtitarEQENOTdPtg/IbXNVud,iv:Z++LbSfC7BhvSiGCN2+kLgb37M95tdwcVZgOtE/qSJM=,tag:s/0E6lYKu+6LbWHpPAJeAA==,type:comment]
  user-mapping.xml: ENC[AES256_GCM,data:gDsIAMx7yTiD09RM/WjLPeVdpoW5cjAmWeDEwKPlNGRgMOq0wb70LRTBvtALZqqwNiLPAKP5MF8HppKKHsCOhzMXaDDmTVZXvTTicpz1u5D18fhXziG0kAAW9iTF3FOsJeL2YC06d8Zayb6bXJu1kt4mGj5/n1X3+Wl4bJsLbXxEV7zv0uYrzIxm4KGAONczApns7WSuHhKqwvy0c2OLUH+RdIlBx6Oa7Yp1jeMgIFeptGzQ/UkhSuQhS9lB27MZF9K/2Bofk04IfcJJJZd4fFqP2ffx8xmGv7I+BUHexHhX3ssiPlkUQCuQhr6PFokA6t8VSI8TBDL0Ul/SqnSlrvCmLFJ0efLGnXPJKa2BCJoRH4Z/jvNHafN8jtkBB0eV0SkSuewio8ojPL4Cz+cnEN+xkOSfC+92M6zMXLSjZGud/h0x0Eq4FfKUWZeA0nwtQde9/3C7zCxpTPHw1w5oOMU2aE4DrcjjSziB3mQeEZhSUJK433GwwmUkewbw1ND2HrAIVJ9eip1jMTD9w42W/0nBhA5jUkyeOe40NjJL1w24QFxATQPmB9hZ,iv:X6d12+1pa5yxq/4/DOaQYYj8U7r6ujCj7NUt/qA2JxQ=,tag:WIFAHDd00PvVKUfrKcfIaQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNkhwcXpNZ2pvcGFOMjg4
        K2NteFFjSnNKTlBCZnlCMGhLZmVjUWFTRUNVCk4yblZLOHRaUGRCKzEvd1RzL1RN
        UXpSemgyTFlRSXQ0dmJBL0pMMHBkZVEKLS0tIDMvVFBhSk9mQTg0TUt2YksxSG5k
        dnBKemI5RjFacThzRm1UMVBZSHNOR0kKAHsH7+zpn4WjCk8X4Uk+gRtJpVzWmWPV
        tMQ3NNdeIsWDx1HXZVErMaDSL711rDfL820Bs0+BupJPjYX2k8+SpA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gekuxnpd95l5j8gsvmpsn2mewnevd0c5y5v66p4trzcqhmpn0svqkmnyy7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-13T01:11:15Z"
  mac: ENC[AES256_GCM,data:Thp+SEQL8yuzahx0wKCOYnfnju2SOADcm2BWBYWj7Z39oWG6pBt4U+rYphdHQIWUXn/qN6FFF97OoNTaxQb4NwciWsm+Yr0LUb9By6KSeDIosr9IDMOojhgL3bTNudHZjAmK8XcBhzojiYOXquuV09jXLzMPehdHN8JJXuea1xc=,iv:KC9bY7CW0eyQCB4GjAEh95heLBNZlua5Vh4QHvSC/44=,tag:o39BK/mSZgsyz97s4eK6Pw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
