# Encrypt with: sops --encrypt --in-place kubernetes/apps/default/autensa/app/secret.sops.yaml
# Generate a gateway token with: openssl rand -hex 32
apiVersion: v1
kind: Secret
metadata:
  name: autensa-secret
  namespace: default
type: Opaque
stringData:
  OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:Awzd7brc4Rm0DHvSkg6tOzj1eDAYypq7cJFtiNcuyw9bT2+5yPdsIvdmcgLkzGI9DYDWb6vW5PWWU/osvlODZg==,iv:O5+NAF8F684KqgdHi0U5BpjZcxf85YEkHk4xYG5S6sg=,tag:Pe3GYuteaIWKuj3W9BYSyg==,type:str]
  ANTHROPIC_API_KEY: ENC[AES256_GCM,data:4xTunkQUsqx7h4cGlUvk9TK3jBajI9Bn/VoYZRbfgk+m4uaLWBtXDqiJ/Qa3cwi+Offy1TmUMiYaLn5+7B/sxfDbzLKjdCJ9Ox2SWn3o79xMwetHqdcVtZyoowOLhWVXwdipmCJc22Uette2,iv:nKpNaAAZu5o0YDn5ErPxxLFIEMikyyvy51A6E5l0sMs=,tag:/jVzJw4DecXoK5jxhgfMDw==,type:str]
sops:
  age:
    - recipient: age1gekuxnpd95l5j8gsvmpsn2mewnevd0c5y5v66p4trzcqhmpn0svqkmnyy7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreW5MeGN2WTR2T0JlNGM0
        ZlpteG95OGFxOHhsSERIdCtLd0E1cGlUZGs0CkNISytRU0p1N24rUlhVb0Q4SDdz
        QlpXbWtwamk2eVRnMUtnYWpCZ21yS0EKLS0tIHdCc0xrUnVOUzRPVG1tY3c4RW41
        TWNtYlhGSzVWd3RhS2wzS1dXMDZOczAKCl5qlWroX80T/YP9Ao5vS6QFJQ+cYhAR
        ZMBWb8j1C6EL5ToCJKLWr+6LptnnDEpU9nrgjW9oYjKqDNO4lVilUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T02:07:47Z"
  mac: ENC[AES256_GCM,data:yTkxwIZbH/S5xU5ITr0P/fRN/LXHA9cfPo3jrGDQjF/hYD9S5DkBWrmNT7cfykXDrKxB686N0zY04l+UZVjnltI8gmPVGZQSU0zJBxzvxDfLeVR3vhp/9XPUwdEtTjwTTAKfCjamfTalj/liCgM6XhSySJYIvMVDmy5ykGn2a+A=,iv:uN1gD6RsfK3RVZY+G7pYSQYjDQUpE5cUZo+Y8zxSOAg=,tag:S6kkD3vg5fQmtYXNYJnN/w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
