---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:PLACEHOLDER==,iv:PLACEHOLDER+PLACEHOLDER+PLACEHOLDER==,tag:PLACEHOLDER+PLACEHOLDERk=,type:str]
    admin-password: ENC[AES256_GCM,data:PLACEHOLDER==,iv:PLACEHOLDER+PLACEHOLDER+PLACEHOLDER==,tag:PLACEHOLDER+PLACEHOLDERk=,type:str]
sops:
    age:
        - recipient: age1gekuxnpd95l5j8gsvmpsn2mewnevd0c5y5v66p4trzcqhmpn0svqkmnyy7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            PLACEHOLDER/THIS/FILE/MUST/BE/ENCRYPTED/WITH/SOPS/BEFORE/DEPLOYING==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T00:00:00Z"
    mac: ENC[AES256_GCM,data:PLACEHOLDER==,iv:PLACEHOLDER+PLACEHOLDER+PLACEHOLDER==,tag:PLACEHOLDER+PLACEHOLDERk=,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
