apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:f42Fdt9wRqZNMEwg/w==,iv:UH6rmAJx7j7qexK337epDjySbon75hh2PPAd2KCqjK8=,tag:exzT0Vb621zb+uNEO9AenA==,type:str]
  admin-password: ENC[AES256_GCM,data:UGe1wDtxhSWZfb9MzHWRVkvGR63nuS6c46vKt/4=,iv:lwUTLVnWV1F43Y1yds8BBwDJXquq2Q4KNnCVgzmtdgU=,tag:7mlgrFwQnscjI7s3HJOqBw==,type:str]
sops:
  age:
    - recipient: age1gekuxnpd95l5j8gsvmpsn2mewnevd0c5y5v66p4trzcqhmpn0svqkmnyy7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNGl0bmE2czl4My9VcFNa
        dEhFMTFVb0JnM3NjMDZTaUcxaEdIaFBIZENZCjJEajFuc1dmeWFaZ3hUYmI1dUw5
        NTc5OWlaTFpCYXc3NHd1RzhZSkRTR2sKLS0tIHlTbTI5ay9ubGxuTmxvT2pUbDRy
        SGJ4VUNWSytmMXVYVjRsN09VSTRqcVkKB/NDazD5xT5xB5WocjbxtRA4yECUwhC8
        HV4Tw/DQmNZ19umCrAAhhq/OmwTXAP4oe2D/taiUNkQMmR+aY6Zqhw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T03:35:37Z"
  mac: ENC[AES256_GCM,data:zpMjjaXEbGA8sa0O/89ulzJGAwiCh8Fr0nfekUhEGDrCRjG8a/IieNLHUA0k2d3qz+Rx5qFr+tVaTgDBepOdiIhVy41WsR4X7QXFAMT/7+wIA7bdVuvnLhZGreXdo806tYFxXeYpslE+TNosLCegyaoflFwlcnb/GUWRl8qeGm4=,iv:KIuPxt4pgN8X11nQF5MQaa7cQH00k/nIg8xsHXw9CMg=,tag:bQH8DcV+ghP/dQqSLMFz0g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
