apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:f42Fdt9wRqZNMEwg/w==,iv:UH6rmAJx7j7qexK337epDjySbon75hh2PPAd2KCqjK8=,tag:exzT0Vb621zb+uNEO9AenA==,type:str]
    admin-password: ENC[AES256_GCM,data:4rajdZEP03+CE2vcN36dpunfp6xnVuPJ,iv:ajbVtmbRuBTrsKTu2b5UiDRdd7WwKv3X4cIO7MpQR2Q=,tag:Bv+P4/zeh58DM9l2VUBqNQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNGl0bmE2czl4My9VcFNa
            dEhFMTFVb0JnM3NjMDZTaUcxaEdIaFBIZENZCjJEajFuc1dmeWFaZ3hUYmI1dUw5
            NTc5OWlaTFpCYXc3NHd1RzhZSkRTR2sKLS0tIHlTbTI5ay9ubGxuTmxvT2pUbDRy
            SGJ4VUNWSytmMXVYVjRsN09VSTRqcVkKB/NDazD5xT5xB5WocjbxtRA4yECUwhC8
            HV4Tw/DQmNZ19umCrAAhhq/OmwTXAP4oe2D/taiUNkQMmR+aY6Zqhw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gekuxnpd95l5j8gsvmpsn2mewnevd0c5y5v66p4trzcqhmpn0svqkmnyy7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T14:37:18Z"
    mac: ENC[AES256_GCM,data:ZIG0aY8oDTFM7YeYqZnuwxsCwwsB79ksn3V24nSQekdyo1HKZz56DulsljfAa386+0ZeZK/G7BsLUBt23cRfc2xzpAjyl/pPSMJFKPwfbcaSakxpYUpXCemb6fQ7DXMl/y7TdQIyqQIZSTDc4uP9vA8ec0TAmjIMTO0F7dLolGA=,iv:BkdzZQx36qZxMnOAkEhWkxJQsry3We3Q0ApcaPSvmkM=,tag:dQ35r4wj2eBXmt91WvWSfw==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
