---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrepository.yaml
  - ./helmrelease-crds.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./httproute-prometheus.yaml
  - ./grafana-secret.sops.yaml
