---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./secret.sops.yaml
  - ./secret-auth-token.sops.yaml
  # - ./rbac.yaml   # only if the server talks to the Kubernetes API
