---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: knative-serving
spec:
  dependsOn:
    - name: knative-operator
  healthChecks:
    - apiVersion: operator.knative.dev/v1beta1
      kind: KnativeServing
      name: knative-serving
      namespace: knative-serving
  interval: 1h
  path: ./kubernetes/apps/serverless/knative-serving/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: knative-serving
  wait: false
