---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metube-downloads
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn-scratch
