---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thanos-compactor-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 30Gi
  storageClassName: longhorn-scratch
