---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  docker.yaml: ""

  kubernetes.yaml: |
    mode: cluster
    gateway: true
    ingress: false
    traefik: false

  settings.yaml: |
    title: Homelab
    # background:
    #   image: https://raw.githubusercontent.com/joryirving/home-ops/main/.docs/assets/101518784_p0.jpg
    #   opacity: 20
    favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/heimdall.png
    theme: dark
    color: slate
    headerStyle: clean
    statusStyle: dot
    useEqualHeights: false
    fiveColumns: true
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
    providers:
      longhorn:
        url: http://longhorn-frontend.storage.svc.cluster.local
    layout:
      Home Automation:
        style: column
        icon: home-assistant
      Networking:
        style: column
        icon: opnsense
      LLM/Ai:
        style: column
        icon: open-webui
      Apps:
        style: column
        icon: immich
      Security:
        style: column
        icon: pocket-id
      Social:
        style: column
        icon: mastodon
      Media:
        style: column
        icon: jellyfin
      Downloads:
        style: column
        icon: sonarr
      Monitoring:
        style: column
        icon: grafana
      Storage:
        style: column
        icon: longhorn
      Kubernetes:
        style: column
        icon: kubernetes

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true

  bookmarks.yaml: ""

  services.yaml: |
    - Home:
        - Home Assistant:
            icon: home-assistant
            href: https://ha.koopmans.co
            description: Smart Home Hub
        - Printer:
            icon: hp
            href: https://hp476.koopmans.co
            description: HP Printer Configuration
    - Networking:
        - OPNsense:
            icon: opnsense
            href: https://192.168.1.1:8443
            description: Router & Firewall
        - Proxmox:
            icon: proxmox
            href: https://vm01.koopmans.co:8006
            description: Virtualization Management
        - Omada:
            icon: tp-link
            href: https://docker01:8043
            description: Wireless Controller
        - Portainer:
            icon: portainer
            href: https://docker01:9443
            description: Container and Controller Management
    - Media:
        - Plex:
            icon: plex
            href: https://app.plex.tv/desktop
            description: Streaming Media Server
    - Storage:
        - Longhorn:
            icon: longhorn
            href: https://longhorn.koopmans.co
            description: Distributed Block Storage
