apiVersion: v1
kind: Secret
metadata:
  name: postgres-s3-backup-secret
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:mdqu07im2C59xkujP39Z1oHo8lg=,iv:mHkhDESh51WHO0QzULNCJUaL6BnytJpYy127q7uUWQo=,tag:CRnSmxDLXVTshACOCLTMSg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:qrplidDZNHuYlqiE22Vb3WU5EBY9BZeWTxT9j+ozp1rLLQqeVHsJWA==,iv:Kh9xMWkkGJJECMYYBGCcL5HL0H4c59PmC4+h/WsXdac=,tag:ECkWkzSv12u3iK7bfX+MnA==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:HfmDW3ELae+O,iv:e1t/kBH7Hnk9hqX/lEp169QhRFVCKJrzfUgYRAsNqTM=,tag:WlGlDYo6VfnZxoLV0oA2fg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcC9zUTUrMDl4aGdGSmp1
        QXN6VjFYWDlVbVZVby9IdTA0TGtHbTJ2V0E0CnRNaGJXazdjZ3I4UG9VR28yNmQ1
        QlA0eUUxVHVJdjRJcGxDcldiZFhHY1kKLS0tIHVoZkxFOVJHRzhtRFFUM0orWVpz
        SzRuSzA4RzlUOExZTk9wMm8vQ2lsdGsKXShSKyd22dd4Yra/+2bjldSPUL9mSHfY
        nrv5cE9uS0cuCe1BUKc5fadvbqpN1fTkKyqeY2XaPlyCNm5g7O58cw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1gekuxnpd95l5j8gsvmpsn2mewnevd0c5y5v66p4trzcqhmpn0svqkmnyy7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-23T17:29:54Z"
  mac: ENC[AES256_GCM,data:16sJTZeNeYJJnMSKcZgTET0wlDtYmrJ1CbVvZ3mtdLpGhws2M+jTvSI9AqTN2sFLHnAXbgEVwJQhgoSrNHC+ZW0FsbAHcRq0dqvpHPrIWcAWM28xqROf8NAuXWknQYdKIQyfApLt35O8xqOgJYSrWJ33EY7FT2L5DSjNZN/2/go=,iv:r90DEawGlTnXBryxQClsMEOmaCxmt/9wlukMiOMKp14=,tag:gUU49/sNQp4Zbx6oaV9pBg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
